# Neon storefront sign generator — the established style: 384x256,
# near-black card, Impact text in white with a colored neon glow, and a
# simple line-art glyph below in the accent color.
#
# The original downtown batch (commit 7a1f556) was generated by an unsaved
# one-off; this is the reconstruction. Run from the repo root:
#   python research/store-signs/make_signs.py
from PIL import Image, ImageDraw, ImageFilter, ImageFont

W, H = 384, 256
BG = (10, 10, 15, 255)
FONT = "C:/Windows/Fonts/impact.ttf"


def neon_text(base, text, cy, size, color, fill=(245, 240, 235)):
    font = ImageFont.truetype(FONT, size)
    tmp = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    d = ImageDraw.Draw(tmp)
    bbox = d.textbbox((0, 0), text, font=font, stroke_width=6)
    x = (W - (bbox[2] - bbox[0])) // 2 - bbox[0]
    y = cy - (bbox[3] - bbox[1]) // 2 - bbox[1]
    d.text((x, y), text, font=font, fill=color, stroke_width=6, stroke_fill=color)
    glow = tmp.filter(ImageFilter.GaussianBlur(9))
    base.alpha_composite(glow)
    base.alpha_composite(glow)
    d2 = ImageDraw.Draw(base)
    d2.text((x, y), text, font=font, fill=color, stroke_width=6, stroke_fill=color)
    d2.text((x, y), text, font=font, fill=fill, stroke_width=2, stroke_fill=fill)


def neon_lines(base, segs, color, width=5):
    tmp = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    d = ImageDraw.Draw(tmp)
    for seg in segs:
        d.line(seg, fill=color, width=width, joint="curve")
    glow = tmp.filter(ImageFilter.GaussianBlur(7))
    base.alpha_composite(glow)
    base.alpha_composite(glow)
    base.alpha_composite(tmp)


def neon_ellipse(base, box, color, width=5):
    tmp = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    ImageDraw.Draw(tmp).ellipse(box, outline=color, width=width)
    glow = tmp.filter(ImageFilter.GaussianBlur(7))
    base.alpha_composite(glow)
    base.alpha_composite(glow)
    base.alpha_composite(tmp)


def card():
    return Image.new("RGBA", (W, H), BG)


def save(img, name):
    img.convert("RGB").save(f"assets/world/signs/{name}.png")
    print(name, "written")


# OMNICORP — cold corporate cyan-blue, globe glyph
img = card()
blue = (70, 170, 255)
neon_text(img, "OMNI", 52, 64, blue)
neon_text(img, "CORP", 110, 44, blue)
cx, cy, r = W // 2, 192, 40
neon_ellipse(img, (cx - r, cy - r, cx + r, cy + r), blue)
neon_lines(img, [
    [(cx - r + 6, cy - 16), (cx + r - 6, cy - 16)],
    [(cx - r, cy), (cx + r, cy)],
    [(cx - r + 6, cy + 16), (cx + r - 6, cy + 16)],
], blue, width=4)
neon_ellipse(img, (cx - 16, cy - r, cx + 16, cy + r), blue, width=4)
save(img, "omnicorp")

# NEXUS TOWER — abandoned: pale desaturated violet, tower glyph
img = card()
pale = (150, 140, 190)
neon_text(img, "NEXUS", 52, 62, pale, fill=(210, 205, 220))
neon_text(img, "TOWER", 110, 42, pale, fill=(210, 205, 220))
cx = W // 2
neon_lines(img, [
    [(cx - 26, 228), (cx - 26, 168), (cx - 12, 150), (cx - 12, 228)],
    [(cx + 26, 228), (cx + 26, 168), (cx + 12, 150), (cx + 12, 228)],
    [(cx - 12, 150), (cx + 12, 150)],
    [(cx, 150), (cx, 132)],
], pale, width=4)
save(img, "nexus")

# CORTEX HQ — hot magenta (matches the corpo dungeon accents), circuit glyph
img = card()
mag = (255, 60, 200)
neon_text(img, "CORTEX", 52, 62, mag)
neon_text(img, "HQ", 110, 44, mag)
cx, cy = W // 2, 190
neon_lines(img, [
    [(cx - 30, cy - 26), (cx + 30, cy - 26), (cx + 30, cy + 26),
     (cx - 30, cy + 26), (cx - 30, cy - 26)],
    [(cx - 52, cy - 14), (cx - 30, cy - 14)],
    [(cx - 52, cy + 14), (cx - 30, cy + 14)],
    [(cx + 30, cy - 14), (cx + 52, cy - 14)],
    [(cx + 30, cy + 14), (cx + 52, cy + 14)],
    [(cx - 12, cy - 26), (cx - 12, cy - 44)],
    [(cx + 12, cy - 26), (cx + 12, cy - 44)],
], mag, width=4)
neon_ellipse(img, (cx - 12, cy - 12, cx + 12, cy + 12), mag, width=4)
save(img, "cortex")
